# Copyright (C) 2015-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lenovo/a6010/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/lenovo/a6010

PRODUCT_COPY_FILES += \
    vendor/lenovo/a6010/proprietary/vendor/firmware/venus.b00:system/vendor/firmware/venus.b00 \
    vendor/lenovo/a6010/proprietary/vendor/firmware/venus.b01:system/vendor/firmware/venus.b01 \
    vendor/lenovo/a6010/proprietary/vendor/firmware/venus.b02:system/vendor/firmware/venus.b02 \
    vendor/lenovo/a6010/proprietary/vendor/firmware/venus.b03:system/vendor/firmware/venus.b03 \
    vendor/lenovo/a6010/proprietary/vendor/firmware/venus.b04:system/vendor/firmware/venus.b04 \
    vendor/lenovo/a6010/proprietary/vendor/firmware/venus.mbn:system/vendor/firmware/venus.mbn \
    vendor/lenovo/a6010/proprietary/vendor/firmware/venus.mdt:system/vendor/firmware/venus.mdt

PRODUCT_COPY_FILES += \
    vendor/lenovo/a6010/proprietary/vendor/bin/hw/android.hardware.bluetooth@1.0-service-qti-lazy:system/vendor/bin/hw/android.hardware.bluetooth@1.0-service-qti-lazy \
    vendor/lenovo/a6010/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti-lazy.rc:system/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti-lazy.rc \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.hardware.fm@1.0.so:system/vendor/lib/vendor.qti.hardware.fm@1.0.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.hardware.bluetooth_sar@1.0.so:system/vendor/lib/vendor.qti.hardware.bluetooth_sar@1.0.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.hardware.btconfigstore@1.0.so:system/vendor/lib/vendor.qti.hardware.btconfigstore@1.0.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqti_vndfwk_detect.so:system/vendor/lib/libqti_vndfwk_detect.so \
    vendor/lenovo/a6010/proprietary/vendor/bin/adsprpcd:system/vendor/bin/adsprpcd \
    vendor/lenovo/a6010/proprietary/vendor/bin/mm-qcamera-daemon:system/vendor/bin/mm-qcamera-daemon \
    vendor/lenovo/a6010/proprietary/vendor/bin/qseecomd:system/vendor/bin/qseecomd \
    vendor/lenovo/a6010/proprietary/vendor/bin/vm_bms:system/vendor/bin/vm_bms \
    vendor/lenovo/a6010/proprietary/vendor/firmware/a300_pfp.fw:system/vendor/firmware/a300_pfp.fw \
    vendor/lenovo/a6010/proprietary/vendor/firmware/a300_pm4.fw:system/vendor/firmware/a300_pm4.fw \
    vendor/lenovo/a6010/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:system/vendor/firmware/cpp_firmware_v1_1_1.fw \
    vendor/lenovo/a6010/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:system/vendor/firmware/cpp_firmware_v1_1_6.fw \
    vendor/lenovo/a6010/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:system/vendor/firmware/cpp_firmware_v1_2_0.fw \
    vendor/lenovo/a6010/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:system/vendor/firmware/cpp_firmware_v1_4_0.fw \
    vendor/lenovo/a6010/proprietary/vendor/bin/hw/vendor.qti.hardware.perf@1.0-service:system/vendor/bin/hw/vendor.qti.hardware.perf@1.0-service \
    vendor/lenovo/a6010/proprietary/vendor/etc/init/vendor.qti.hardware.perf@1.0-service.rc:system/vendor/etc/init/vendor.qti.hardware.perf@1.0-service.rc \
    vendor/lenovo/a6010/proprietary/vendor/etc/perf/perfboostsconfig.xml:system/vendor/etc/perf/perfboostsconfig.xml \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqti_performance.so:system/vendor/lib/libqti_performance.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libperfgluelayer.so:system/vendor/lib/libperfgluelayer.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqti-perfd.so:system/vendor/lib/libqti-perfd.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqti-util.so:system/vendor/lib/libqti-util.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqti-utils.so:system/vendor/lib/libqti-utils.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.hardware.perf@1.0.so:system/vendor/lib/vendor.qti.hardware.perf@1.0.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/egl/libESXEGL_adreno.so:system/vendor/lib/egl/libESXEGL_adreno.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib/egl/libESXGLESv1_CM_adreno.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/egl/libESXGLESv2_adreno.so:system/vendor/lib/egl/libESXGLESv2_adreno.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/egl/libQTapGLES.so:system/vendor/lib/egl/libQTapGLES.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/egl/libRBEGL_adreno.so:system/vendor/lib/egl/libRBEGL_adreno.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib/egl/libRBGLESv1_CM_adreno.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/egl/libRBGLESv2_adreno.so:system/vendor/lib/egl/libRBGLESv2_adreno.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.hardware.iop@1.0_vendor.so:system/vendor/lib/vendor.qti.hardware.iop@1.0_vendor.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.hardware.iop@2.0_vendor.so:system/vendor/lib/vendor.qti.hardware.iop@2.0_vendor.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqti-iopd-client.so:system/vendor/lib/libqti-iopd-client.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqti-iopd.so:system/vendor/lib/libqti-iopd.so \
    vendor/lenovo/a6010/proprietary/vendor/bin/hw/vendor.qti.hardware.iop@1.0-service:system/vendor/bin/hw/vendor.qti.hardware.iop@1.0-service \
    vendor/lenovo/a6010/proprietary/vendor/etc/init/vendor.qti.hardware.iop@1.0-service.rc:system/vendor/etc/init/vendor.qti.hardware.iop@1.0-service.rc \
    vendor/lenovo/a6010/proprietary/vendor/lib/hw/vendor.qti.hardware.iop@1.0-impl.so:system/vendor/lib/hw/vendor.qti.hardware.iop@1.0-impl.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/com.qualcomm.qti.bluetooth_audio@1.0.so:system/vendor/lib/com.qualcomm.qti.bluetooth_audio@1.0.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/hw/android.hardware.bluetooth@1.0-impl-qti.so:system/vendor/lib/hw/android.hardware.bluetooth@1.0-impl-qti.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libcalmodule_common.so:system/vendor/lib/libcalmodule_common.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libcalmodule_akm.so:system/vendor/lib/libcalmodule_akm.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libactuator_dw9718s_2gong_camcorder.so:system/vendor/lib/libactuator_dw9718s_2gong_camcorder.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libactuator_dw9718s_2gong_camera.so:system/vendor/lib/libactuator_dw9718s_2gong_camera.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libactuator_dw9718s_2gong.so:system/vendor/lib/libactuator_dw9718s_2gong.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libactuator_dw9718s_camcorder.so:system/vendor/lib/libactuator_dw9718s_camcorder.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libactuator_dw9718s_camera.so:system/vendor/lib/libactuator_dw9718s_camera.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libactuator_dw9718s.so:system/vendor/lib/libactuator_dw9718s.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libactuator_dw9761_ofilm.so:system/vendor/lib/libactuator_dw9761_ofilm.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libactuator_dw9761_ofilm_camcorder.so:system/vendor/lib/libactuator_dw9761_ofilm_camcorder.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libactuator_dw9761_ofilm_camera.so:system/vendor/lib/libactuator_dw9761_ofilm_camera.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libactuator_dw9714_13p1ba.so:system/vendor/lib/libactuator_dw9714_13p1ba.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libactuator_dw9714_13p1ba_camcorder.so:system/vendor/lib/libactuator_dw9714_13p1ba_camcorder.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libactuator_dw9714_13p1ba_camera.so:system/vendor/lib/libactuator_dw9714_13p1ba_camera.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libactuator_rohm_bu64243gwz.so:system/vendor/lib/libactuator_rohm_bu64243gwz.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so:system/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_camera.so:system/vendor/lib/libactuator_dw9761_ofilm_camera.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_gc2355_8916_common.so:system/vendor/lib/libchromatix_gc2355_8916_common.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_gc2355_8916_default_video.so:system/vendor/lib/libchromatix_gc2355_8916_default_video.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_gc2355_8916_preview.so:system/vendor/lib/libchromatix_gc2355_8916_preview.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_imx219_2gong_common.so:system/vendor/lib/libchromatix_imx219_2gong_common.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_imx219_2gong_default_video.so:system/vendor/lib/libchromatix_imx219_2gong_default_video.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_imx219_2gong_liveshot.so:system/vendor/lib/libchromatix_imx219_2gong_liveshot.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_imx219_2gong_preview.so:system/vendor/lib/libchromatix_imx219_2gong_preview.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_imx219_2gong_snapshot.so:system/vendor/lib/libchromatix_imx219_2gong_snapshot.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_imx219_q8n13a_common.so:system/vendor/lib/libchromatix_imx219_q8n13a_common.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_imx219_q8n13a_default_video.so:system/vendor/lib/libchromatix_imx219_q8n13a_default_video.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_imx219_q8n13a_liveshot.so:system/vendor/lib/libchromatix_imx219_q8n13a_liveshot.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_imx219_q8n13a_preview.so:system/vendor/lib/libchromatix_imx219_q8n13a_preview.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_imx219_q8n13a_snapshot.so:system/vendor/lib/libchromatix_imx219_q8n13a_snapshot.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_common.so:system/vendor/lib/libchromatix_ov5670_q5v41b_common.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_default_video.so:system/vendor/lib/libchromatix_ov5670_q5v41b_default_video.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_liveshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_liveshot.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_preview.so:system/vendor/lib/libchromatix_ov5670_q5v41b_preview.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_snapshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_snapshot.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_video_hd.so:system/vendor/lib/libchromatix_ov5670_q5v41b_video_hd.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_zsl.so:system/vendor/lib/libchromatix_ov5670_q5v41b_zsl.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov13850_common.so:system/vendor/lib/libchromatix_ov13850_common.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov13850_default_video.so:system/vendor/lib/libchromatix_ov13850_default_video.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov13850_preview.so:system/vendor/lib/libchromatix_ov13850_preview.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov13850_snapshot.so:system/vendor/lib/libchromatix_ov13850_snapshot.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov8858_common.so:system/vendor/lib/libchromatix_ov8858_common.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov8858_default_video.so:system/vendor/lib/libchromatix_ov8858_default_video.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov8858_liveshot.so:system/vendor/lib/libchromatix_ov8858_liveshot.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov8858_preview.so:system/vendor/lib/libchromatix_ov8858_preview.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_common.so:system/vendor/lib/libchromatix_ov8858_q8v19w_common.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_default_video.so:system/vendor/lib/libchromatix_ov8858_q8v19w_default_video.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_liveshot.so:system/vendor/lib/libchromatix_ov8858_q8v19w_liveshot.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_preview.so:system/vendor/lib/libchromatix_ov8858_q8v19w_preview.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_snapshot.so:system/vendor/lib/libchromatix_ov8858_q8v19w_snapshot.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_video_nonHD.so:system/vendor/lib/libchromatix_ov8858_q8v19w_video_nonHD.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov8858_q8v19w_zsl.so:system/vendor/lib/libchromatix_ov8858_q8v19w_zsl.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov8858_snapshot.so:system/vendor/lib/libchromatix_ov8858_snapshot.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_common.so:system/vendor/lib/libchromatix_ov8865_q8v18a_common.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so:system/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_preview.so:system/vendor/lib/libchromatix_ov8865_q8v18a_preview.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so:system/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so:system/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libwcnss_qmi.so:system/vendor/lib/libwcnss_qmi.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libuiblur.so:system/vendor/lib/libuiblur.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmm-als.so:system/vendor/lib/libmm-als.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmm-hdcpmgr.so:system/vendor/lib/libmm-hdcpmgr.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera2_imx219_8909_module.so:system/vendor/lib/libmmcamera2_imx219_8909_module.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera_gc2355_8916.so:system/vendor/lib/libmmcamera_gc2355_8916.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera_imx219_q8n13a.so:system/vendor/lib/libmmcamera_imx219_q8n13a.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera_sony_imx219_eeprom.so:system/vendor/lib/libmmcamera_sony_imx219_eeprom.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera_lenovo_ov5670_eeprom.so:system/vendor/lib/libmmcamera_lenovo_ov5670_eeprom.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera_ov5670_q5v41b.so:system/vendor/lib/libmmcamera_ov5670_q5v41b.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera_ov13850.so:system/vendor/lib/libmmcamera_ov13850.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera_ov8865_q8v18a.so:system/vendor/lib/libmmcamera_ov8865_q8v18a.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so:system/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera_wingtech_ov13850_eeprom.so:system/vendor/lib/libmmcamera_wingtech_ov13850_eeprom.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libsd_sdk_display.so:system/vendor/lib/libsd_sdk_display.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libwvhidl.so:system/vendor/lib/libwvhidl.so \
    vendor/lenovo/a6010/proprietary/vendor/bin/hw/android.hardware.drm@1.3-service-lazy.widevine:system/vendor/bin/hw/android.hardware.drm@1.3-service-lazy.widevine \
    vendor/lenovo/a6010/proprietary/vendor/etc/init/android.hardware.drm@1.3-service-lazy.widevine.rc:system/vendor/etc/init/android.hardware.drm@1.3-service-lazy.widevine.rc \
    vendor/lenovo/a6010/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libcpion.so:system/vendor/lib/libcpion.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libcppf.so:system/vendor/lib/libcppf.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libhdcpsrm.so:system/vendor/lib/libhdcpsrm.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/liboemcrypto.so:system/vendor/lib/liboemcrypto.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libtzdrmgenprov.so:system/vendor/lib/libtzdrmgenprov.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/soundfx/libasphere.so:system/vendor/lib/soundfx/libasphere.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libOmxAlacDec.so:system/vendor/lib/libOmxAlacDec.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libOmxAlacDecSw.so:system/vendor/lib/libOmxAlacDecSw.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libOmxAmrwbplusDec.so:system/vendor/lib/libOmxAmrwbplusDec.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libOmxApeDec.so:system/vendor/lib/libOmxApeDec.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libOmxApeDecSw.so:system/vendor/lib/libOmxApeDecSw.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libOmxWmaDec.so:system/vendor/lib/libOmxWmaDec.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libFileMux.so:system/vendor/lib/libFileMux.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libOmxMux.so:system/vendor/lib/libOmxMux.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmmparser_lite.so:system/vendor/lib/libmmparser_lite.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libOmxVpp.so:system/vendor/lib/libOmxVpp.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libvpplibrary.so:system/vendor/lib/libvpplibrary.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libaptX_encoder.so:system/vendor/lib/libaptX_encoder.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libaptXHD_encoder.so:system/vendor/lib/libaptXHD_encoder.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libldacBT_enc.so:system/vendor/lib/libldacBT_enc.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so

# GNSS stack from Jio LS-5701-J (jioospro) Jio/jioospro/jioospro:11/JIO_GO-R.11.00.023.00/2300:user/release-keys
PRODUCT_COPY_FILES += \
    vendor/lenovo/a6010/proprietary/vendor/bin/hw/android.hardware.gnss@2.1-service-qti:system/vendor/bin/hw/android.hardware.gnss@2.1-service-qti \
    vendor/lenovo/a6010/proprietary/vendor/bin/garden_app:system/vendor/bin/garden_app \
    vendor/lenovo/a6010/proprietary/vendor/bin/loc_launcher:system/vendor/bin/loc_launcher \
    vendor/lenovo/a6010/proprietary/vendor/bin/lowi-server:system/vendor/bin/lowi-server \
    vendor/lenovo/a6010/proprietary/vendor/bin/slim_daemon:system/vendor/bin/slim_daemon \
    vendor/lenovo/a6010/proprietary/vendor/bin/xtra-daemon:system/vendor/bin/xtra-daemon \
    vendor/lenovo/a6010/proprietary/vendor/bin/xtwifi-client:system/vendor/bin/xtwifi-client \
    vendor/lenovo/a6010/proprietary/vendor/bin/xtwifi-inet-agent:system/vendor/bin/xtwifi-inet-agent \
    vendor/lenovo/a6010/proprietary/vendor/etc/cacert_location.pem:system/vendor/etc/cacert_location.pem \
    vendor/lenovo/a6010/proprietary/vendor/etc/xtra_root_cert.pem:system/vendor/etc/xtra_root_cert.pem \
    vendor/lenovo/a6010/proprietary/vendor/etc/init/android.hardware.gnss@2.1-service-qti.rc:system/vendor/etc/init/android.hardware.gnss@2.1-service-qti.rc \
    vendor/lenovo/a6010/proprietary/vendor/lib/hw/android.hardware.gnss@2.1-impl-qti.so:system/vendor/lib/hw/android.hardware.gnss@2.1-impl-qti.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/hw/vendor.qti.gnss@4.0-impl.so:system/vendor/lib/hw/vendor.qti.gnss@4.0-impl.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libbatching.so:system/vendor/lib/libbatching.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libcdfw.so:system/vendor/lib/libcdfw.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libcdfw_remote_api.so:system/vendor/lib/libcdfw_remote_api.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libdataitems.so:system/vendor/lib/libdataitems.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libgarden.so:system/vendor/lib/libgarden.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libgarden_haltests_e2e.so:system/vendor/lib/libgarden_haltests_e2e.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libgdtap.so:system/vendor/lib/libgdtap.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libgeofencing.so:system/vendor/lib/libgeofencing.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libgnss.so:system/vendor/lib/libgnss.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libgnsspps.so:system/vendor/lib/libgnsspps.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libgps.utils.so:system/vendor/lib/libgps.utils.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libizat_client_api.so:system/vendor/lib/libizat_client_api.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libloc_api_v02.so:system/vendor/lib/libloc_api_v02.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libloc_core.so:system/vendor/lib/libloc_core.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libloc_socket.so:system/vendor/lib/libloc_socket.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/liblocation_api.so:system/vendor/lib/liblocation_api.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/liblocationservice_glue.so:system/vendor/lib/liblocationservice_glue.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/liblowi_wifihal.so:system/vendor/lib/liblowi_wifihal.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libpdmapper.so:system/vendor/lib/libpdmapper.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libpdnotifier.so:system/vendor/lib/libpdnotifier.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqmi_cci-v30.so:system/vendor/lib/libqmi_cci-v30.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libslimclient.so:system/vendor/lib/libslimclient.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libxtwifi_server_protocol.so:system/vendor/lib/libxtwifi_server_protocol.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libxtwifi_server_protocol_uri_v3.so:system/vendor/lib/libxtwifi_server_protocol_uri_v3.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.gnss@1.0.so:system/vendor/lib/vendor.qti.gnss@1.0.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.gnss@1.1.so:system/vendor/lib/vendor.qti.gnss@1.1.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.gnss@1.2.so:system/vendor/lib/vendor.qti.gnss@1.2.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.gnss@2.0.so:system/vendor/lib/vendor.qti.gnss@2.0.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.gnss@2.1.so:system/vendor/lib/vendor.qti.gnss@2.1.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.gnss@3.0.so:system/vendor/lib/vendor.qti.gnss@3.0.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.gnss@4.0-service.so:system/vendor/lib/vendor.qti.gnss@4.0-service.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.gnss@4.0.so:system/vendor/lib/vendor.qti.gnss@4.0.so

# RIL & QMI stack from msm8916_32 LA.BR.1.2.9.1-02310-8x16.0
PRODUCT_COPY_FILES += \
    vendor/lenovo/a6010/proprietary/system/etc/dpm/dpm.conf:system/etc/dpm/dpm.conf \
    vendor/lenovo/a6010/proprietary/system/etc/dpm/nsrm/NsrmConfiguration.xml:system/etc/dpm/nsrm/NsrmConfiguration.xml \
    vendor/lenovo/a6010/proprietary/system/etc/permissions/privapp-permissions-qti.xml:system/etc/permissions/privapp-permissions-qti.xml \
    vendor/lenovo/a6010/proprietary/system/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    vendor/lenovo/a6010/proprietary/system/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/lenovo/a6010/proprietary/system/etc/permissions/qti_libpermissions.xml:system/etc/permissions/qti_libpermissions.xml \
    vendor/lenovo/a6010/proprietary/system/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/lenovo/a6010/proprietary/system/etc/permissions/telephonyservice.xml:system/etc/permissions/telephonyservice.xml \
    vendor/lenovo/a6010/proprietary/system/etc/sysconfig/qti_whitelist.xml:system/etc/sysconfig/qti_whitelist.xml \
    vendor/lenovo/a6010/proprietary/system/lib/com.qualcomm.qti.dpm.api@1.0.so:system/lib/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/lenovo/a6010/proprietary/system/lib/com.qualcomm.qti.imscmservice@1.0.so:system/lib/com.qualcomm.qti.imscmservice@1.0.so \
    vendor/lenovo/a6010/proprietary/system/lib/com.qualcomm.qti.imscmservice@1.1.so:system/lib/com.qualcomm.qti.imscmservice@1.1.so \
    vendor/lenovo/a6010/proprietary/system/lib/libdpmctmgr.so:system/lib/libdpmctmgr.so \
    vendor/lenovo/a6010/proprietary/system/lib/libdpmfdmgr.so:system/lib/libdpmfdmgr.so \
    vendor/lenovo/a6010/proprietary/system/lib/libdpmframework.so:system/lib/libdpmframework.so \
    vendor/lenovo/a6010/proprietary/system/lib/libdpmnsrm.so:system/lib/libdpmnsrm.so \
    vendor/lenovo/a6010/proprietary/system/lib/libdpmtcm.so:system/lib/libdpmtcm.so \
    vendor/lenovo/a6010/proprietary/system/lib/libqmi_cci_system.so:system/lib/libqmi_cci_system.so \
    vendor/lenovo/a6010/proprietary/system/lib/vendor.qti.hardware.data.latency@1.0.so:system/lib/vendor.qti.hardware.data.latency@1.0.so \
    vendor/lenovo/a6010/proprietary/vendor/bin/dpmQmiMgr:system/vendor/bin/dpmQmiMgr \
    vendor/lenovo/a6010/proprietary/vendor/bin/irsc_util:system/vendor/bin/irsc_util \
    vendor/lenovo/a6010/proprietary/vendor/bin/netmgrd:system/vendor/bin/netmgrd \
    vendor/lenovo/a6010/proprietary/vendor/bin/qmuxd:system/vendor/bin/qmuxd \
    vendor/lenovo/a6010/proprietary/vendor/bin/rmt_storage:system/vendor/bin/rmt_storage \
    vendor/lenovo/a6010/proprietary/vendor/etc/qmi_fw.conf:system/vendor/etc/qmi_fw.conf \
    vendor/lenovo/a6010/proprietary/vendor/lib/com.qualcomm.qti.dpm.api@1.0_vendor.so:system/vendor/lib/com.qualcomm.qti.dpm.api@1.0_vendor.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/com.qualcomm.qti.imscmservice@1.0_vendor.so:system/vendor/lib/com.qualcomm.qti.imscmservice@1.0_vendor.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/com.qualcomm.qti.imscmservice@1.1_vendor.so:system/vendor/lib/com.qualcomm.qti.imscmservice@1.1_vendor.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/com.quicinc.cne.api@1.0.so:system/vendor/lib/com.quicinc.cne.api@1.0.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/com.quicinc.cne.constants@1.0.so:system/vendor/lib/com.quicinc.cne.constants@1.0.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/com.quicinc.cne.constants@2.0.so:system/vendor/lib/com.quicinc.cne.constants@2.0.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/com.quicinc.cne.server@1.0.so:system/vendor/lib/com.quicinc.cne.server@1.0.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/com.quicinc.cne.server@2.0.so:system/vendor/lib/com.quicinc.cne.server@2.0.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libCommandSvc.so:system/vendor/lib/libCommandSvc.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libcne.so:system/vendor/lib/libcne.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libcneoplookup.so:system/vendor/lib/libcneoplookup.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libdiagbridge.so:system/vendor/lib/libdiagbridge.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libdpmqmihal.so:system/vendor/lib/libdpmqmihal.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/liblqe.so:system/vendor/lib/liblqe.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqcmaputils.so:system/vendor/lib/libqcmaputils.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqmi_csvt_srvc.so:system/vendor/lib/libqmi_csvt_srvc.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libril-qc-ltedirectdisc.so:system/vendor/lib/libril-qc-ltedirectdisc.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libril-qc-radioconfig.so:system/vendor/lib/libril-qc-radioconfig.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/librilqmiservices.so:system/vendor/lib/librilqmiservices.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libsettings.so:system/vendor/lib/libsettings.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.hardware.data.latency@1.0_vendor.so:system/vendor/lib/vendor.qti.hardware.data.latency@1.0_vendor.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.hardware.radio.am@1.0_vendor.so:system/vendor/lib/vendor.qti.hardware.radio.am@1.0_vendor.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.hardware.radio.atcmdfwd@1.0_vendor.so:system/vendor/lib/vendor.qti.hardware.radio.atcmdfwd@1.0_vendor.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.hardware.radio.ims@1.0_vendor.so:system/vendor/lib/vendor.qti.hardware.radio.ims@1.0_vendor.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.hardware.radio.lpa@1.0_vendor.so:system/vendor/lib/vendor.qti.hardware.radio.lpa@1.0_vendor.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.hardware.radio.qcrilhook@1.0_vendor.so:system/vendor/lib/vendor.qti.hardware.radio.qcrilhook@1.0_vendor.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.hardware.radio.qtiradio@1.0_vendor.so:system/vendor/lib/vendor.qti.hardware.radio.qtiradio@1.0_vendor.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.hardware.radio.uim@1.0_vendor.so:system/vendor/lib/vendor.qti.hardware.radio.uim@1.0_vendor.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.hardware.radio.uim_remote_client@1.0_vendor.so:system/vendor/lib/vendor.qti.hardware.radio.uim_remote_client@1.0_vendor.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.hardware.radio.uim_remote_server@1.0_vendor.so:system/vendor/lib/vendor.qti.hardware.radio.uim_remote_server@1.0_vendor.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.imsrtpservice@1.0-service-Impl.so:system/vendor/lib/vendor.qti.imsrtpservice@1.0-service-Impl.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/vendor.qti.imsrtpservice@1.0_vendor.so:system/vendor/lib/vendor.qti.imsrtpservice@1.0_vendor.so \
    vendor/lenovo/a6010/proprietary/vendor/radio/qcril_database/qcril.db:system/vendor/radio/qcril_database/qcril.db \
    vendor/lenovo/a6010/proprietary/vendor/lib/libprotobuf-cpp-full-v28.so:system/vendor/lib/libprotobuf-cpp-full-v28.so

# Thermal Engine
PRODUCT_COPY_FILES += \
    vendor/lenovo/a6010/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
    vendor/lenovo/a6010/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so

# GNU parted
PRODUCT_COPY_FILES += \
    vendor/lenovo/a6010/proprietary/vendor/bin/parted:system/vendor/bin/parted

# OMX Qcom HEVC decoder
PRODUCT_COPY_FILES += \
    vendor/lenovo/a6010/proprietary/vendor/lib/libHevcSwDecoder.so:system/vendor/lib/libHevcSwDecoder.so \
    vendor/lenovo/a6010/proprietary/vendor/lib/libOmxVdecHevc.so:system/vendor/lib/libOmxVdecHevc.so

# Dolby Atmos
PRODUCT_COPY_FILES += \
	vendor/lenovo/a6010/proprietary/vendor/lib/libdapparamstorage.so:system/vendor/lib/libdapparamstorage.so \
	vendor/lenovo/a6010/proprietary/vendor/lib/libdlbdsservice.so:system/vendor/lib/libdlbdsservice.so \
	vendor/lenovo/a6010/proprietary/vendor/lib/libstagefright_soft_ddpdec.so:system/vendor/lib/libstagefright_soft_ddpdec.so \
	vendor/lenovo/a6010/proprietary/vendor/lib/libstagefrightdolby.so:system/vendor/lib/libstagefrightdolby.so \
	vendor/lenovo/a6010/proprietary/vendor/lib/soundfx/libatmos.so:system/vendor/lib/soundfx/libatmos.so \
	vendor/lenovo/a6010/proprietary/vendor/lib/vendor.dolby.hardware.dms@1.0-impl.so:system/vendor/lib/vendor.dolby.hardware.dms@1.0-impl.so \
	vendor/lenovo/a6010/proprietary/vendor/lib/vendor.dolby.hardware.dms@1.0.so:system/vendor/lib/vendor.dolby.hardware.dms@1.0.so \
	vendor/lenovo/a6010/proprietary/vendor/bin/hw/vendor.dolby.hardware.dms@1.0-service:system/vendor/bin/hw/vendor.dolby.hardware.dms@1.0-service \
	vendor/lenovo/a6010/proprietary/vendor/etc/init/vendor.dolby.hardware.dms@1.0-service.rc:system/vendor/etc/init/vendor.dolby.hardware.dms@1.0-service.rc \
	vendor/lenovo/a6010/proprietary/vendor/etc/dolby/dap-default.xml:system/vendor/etc/dolby/dap-default.xml \
	vendor/lenovo/a6010/proprietary/vendor/etc/media_codecs_dolby_audio.xml:system/vendor/etc/media_codecs_dolby_audio.xml \
	vendor/lenovo/a6010/proprietary/system/etc/permissions/dolby_dax.xml:system/etc/permissions/dolby_dax.xml \
	vendor/lenovo/a6010/proprietary/system/etc/permissions/privapp-com.dolby.atmos.xml:system/etc/permissions/privapp-com.dolby.atmos.xml \
	vendor/lenovo/a6010/proprietary/system/etc/permissions/privapp-com.dolby.daxservice.xml:system/etc/permissions/privapp-com.dolby.daxservice.xml \
	vendor/lenovo/a6010/proprietary/system/etc/sysconfig/config-com.dolby.atmos.xml:system/etc/sysconfig/config-com.dolby.atmos.xml \
	vendor/lenovo/a6010/proprietary/system/etc/sysconfig/config-com.dolby.daxappui.xml:system/etc/sysconfig/config-com.dolby.daxappui.xml \
	vendor/lenovo/a6010/proprietary/system/etc/sysconfig/config-com.dolby.daxservice.xml:system/etc/sysconfig/config-com.dolby.daxservice.xml

PRODUCT_PACKAGES += \
	DaxUI \
	daxService \
	dolby_dax
# END Dolby Atmos

PRODUCT_PACKAGES += \
    shutdownlistener \
    qcnvitems \
    qcrilhook \
    QtiTelephonyServicelibrary \
    QtiTelephonyService \
    qcrilmsgtunnel \
    vendor.qti.hardware.iop@1.0 \
    vendor.qti.hardware.iop@2.0 \
    sensors.a6000__
