# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oppo/A37/setup-makefiles.sh

ifeq ($(WITH_TWRP),true)
TARGET_RECOVERY_DEVICE_DIRS += vendor/oppo/A37/proprietary
endif
